<a href="https://colab.research.google.com/github/harsh-24-design/Game-Loot/blob/main/crop_yield.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [37]:
import os
print(os.getcwd())
print(os.listdir())

/content/Crop_Yield_Prediction
['crop_modified.csv', 'README.md', 'crop_yield.ipynb', '.git']

In [38]:
!git clone https://github.com/Buelah2245/Crop_Yield_Prediction.git

Cloning into 'Crop_Yield_Prediction'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 20 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 2.16 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [39]:
%cd Crop_Yield_Prediction

/content/Crop_Yield_Prediction/Crop_Yield_Prediction

In [40]:
!ls

crop_modified.csv  crop_yield.ipynb  README.md

In [41]:
import pandas as pd

df = pd.read_csv("crop_modified.csv")
df.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,cat_crop
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0,Nuts
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0,Pulses
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0,Cereal
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0,Fruits
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0,Nuts

In [42]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242361 entries, 0 to 242360
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     242361 non-null  object
 1   District_Name  242361 non-null  object
 2   Crop_Year      242361 non-null  int64
 3   Season         242361 non-null  object
 4   Crop           242361 non-null  object
 5   Area           242361 non-null  float64
 6   Production     242361 non-null  float64
 7   cat_crop       242361 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 14.8+ MB

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
cat_crop         0
dtype: int64

In [43]:
df = df.dropna()

In [44]:
label_encoders = {}

categorical_cols = ['State_Name', 'District_Name', 'Season', 'Crop']

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [45]:
df = df.drop(columns=['cat_crop'])
X = df.drop(columns=['Production'])
y = df['Production']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [47]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [48]:
y_pred = model.predict(X_test)

In [49]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Evaluation Metrics:")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R2 Score: {r2}")

Model Evaluation Metrics:
Mean Absolute Error (MAE): 143647.30782612588
Root Mean Squared Error (RMSE): 5520872.609416016
R2 Score: 0.9242179468247388

In [52]:
model.score(X_test, y_test)

0.9242179468247388

In [55]:
print(X.columns)

Index(['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop', 'Area'], dtype='object')

In [57]:
for i in range(10):

    sample = X.iloc[[i]]

    actual = y.iloc[i]

    predicted = model.predict(sample)

    print(f"Actual: {actual} | Predicted: {predicted[0]}")

Actual: 2000.0 | Predicted: 1914.73
Actual: 1.0 | Predicted: 2.0718
Actual: 321.0 | Predicted: 278.11
Actual: 641.0 | Predicted: 1065.85
Actual: 165.0 | Predicted: 182.355
Actual: 65100000.0 | Predicted: 66064158.88
Actual: 100.0 | Predicted: 157.62
Actual: 2.0 | Predicted: 18.136
Actual: 15.0 | Predicted: 27.78
Actual: 169.0 | Predicted: 220.65

In [76]:
import joblib

joblib.dump(model, "crop_model.pkl", compress=9)

['crop_model.pkl']

In [77]:
!ls

crop_model.pkl	   crop_yield.ipynb	 README.md
crop_modified.csv  crop_yield_model.pkl

In [78]:
from google.colab import files

files.download("crop_yield_model.pkl")